//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int IdSt { get; set; }
        public string NameSt { get; set; }
        public Nullable<System.DateTime> BirthdateSt { get; set; }
        public string AddressSt { get; set; }
        public Nullable<System.DateTime> CreateDateSt { get; set; }
        public Nullable<int> IdCr { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
    }
}
